### ISSUE TITLE
Ubuntu boundary-meter package has been renamed

### ISSUE THREAD

**Issue by flibbertigibbet** [boundary/boundary_scripts#19]
Currently running the `setup_meter.sh` script on Ubuntu 14.04 fails with `Package 'boundary-meter' has no installation candidate`. Apt says that `truesight-meter` replaces it. Docs still reference `boundary-meter` as well.

**Comment by pbarry-r7** [comment]
Could you verify that the system(s) in question are pointing to the staging meter repositories (as opposed to production)?  File /etc/apt/sources.list.d/boundary.list should contain this info (e.g. a URL in there of apt.boundary.com is the production meter repos, a URL of apt-staging.boundary.com is the staging meter repos).  Thx.

**Comment by flibbertigibbet** [comment]
I'm seeing https://apt-staging.boundary.com/ubuntu/ in `/etc/apt/sources.ist.d/boundary.list`.

**Comment by pbarry-r7** [comment]
Cool, yeah, that points to the latest "beta" version of the meter.  BMC is in the process of renaming the meter, and the staging repos have been updated with the new meter package.

The setup_meter.sh file in this repo is no longer actively maintained and out of date.  You can download the latest setup_meter.sh script via this URL:

http://meter.truesight.bmc.com/setup_meter

I believe the setup_meter.sh script will be updated to reference the new meter package once the renamed meter packages make it into the production repos.  For now, I believe you can do an _apt-get update_ and _apt-get install truesight-meter_ to update the meter on your system(s).

**Comment by flibbertigibbet** [comment]
Okay, great. You might want to update the docs at https://help.truesight.bmc.com/hc/en-us/articles/201549062-BMC-TrueSight-Pulse-Meter-Clean-Install-for-Linux to reference the new script URL.

**Comment by pbarry-r7** [comment]
Absolutely, thank you for bringing that up.  Also, if you don't have a need to be on the "staging" version of the meter, you should be able to change the URL in /etc/apt/sources.list.d/boundary.list to remove '-staging' (e.g. https://apt.boundary.com/ubuntu/), then _apt-get update_ and _apt-get install boundary-meter_ and that should ensure you have the latest production meter on your system(s).

**Comment by flibbertigibbet** [comment]
Okay, thanks! This is for a clean install, so I can just point to the new installer script.

**Comment by pbarry-r7** [comment]
:+1:
